global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: shards
    honor_labels: true
    metrics_path: /federate
    params:
      match[]:
        - '{__name__=~"^node_.+_info$"}'
    static_configs:
      - targets:
        - shard01:9090
        - shard02:9090
